default_language_version:
  python: python3.7
default_stages: [commit]
repos:
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        name: black
        language: system
        entry: black
        types: [python]
  - repo: https://gitlab.com/pycqa/flake8
    rev: '3.7.7'
    hooks:
      - id: flake8
